module Musicology
  # Sources:
  # * https://github.com/ianring/PHPMusicTools/blob/master/src/PHPMusicTools/classes/Scale.php
  # * http://www.pdmusic.org/theory.html
  # * http://www.pdmusic.org/text/027.txt
  NAMED_SCALES = {
    273 => ["augmented triad"],
    395 => ["balinese"],
    397 => ["hirajoshi"],
    419 => ["japanese (a)"],
    421 => ["japenese (b)"],
    585 => ["diminished seventh"],
    653 => ["kumoi"],
    661 => ["pentatonic major"],
    819 => ["augmented inverse", "six tone symmetrical"],
    859 => ["ultralocrian", "superlocrian 𝄫7", "diminished"],
    935 => ["mela kanakangi (1)"],
    939 => ["mela senavati (7)"],
    941 => ["mela jhankaradhvani (19)"],
    947 => ["mela gayakapriya (13)"],
    949 => ["mela mararanjani (25)"],
    953 => ["mela yagapriya (31)"],
    967 => ["mela salagam (37)"],
    971 => ["mela gavambodhi (43)"],
    973 => ["mela syamalangi (55)"],
    979 => ["mela dhavalambari (49)"],
    981 => ["mela kantamani (61)"],
    985 => ["mela sucharitra (67)"],
    1123 => ["iwato"],
    1187 => ["insen"],
    1189 => ["egyptian"],
    1193 => ["pentatonic minor"],
    1235 => ["tritone scale"],
    1257 => ["blues"],
    1365 => ["whole tone", "auxiliary augmented"],
    1371 => ["altered", "diminished whole tone", "super locrian"],
    1387 => ["locrian", "half diminished (locrian)"],
    1389 => ["half diminished", "locrian ♯2"],
    1395 => ["oriental (a)"],
    1397 => ["major locrian", "arabian b"],
    1403 => ["eight tone spanish"],
    1447 => ["mela ratnangi (2)"],
    1451 => [
      "phrygian",
      "bhairavi theta",
      "mela hanumattodi (8)",
      "neopolitan minor",
    ],
    1453 => [
      "aeolian",
      "natural minor",
      "asavari theta",
      "ethiopian (geez & ezel)",
      "mela natabhairavi (20)",
      "pure minor",
    ],
    1459 => [
      "phrygian dominant",
      "mela vakulabharanam (14)",
      "spanish gypsy",
      "spanish romani",
      "jewish (ahaba rabba)",
    ],
    1461 => ["hindu", "hindustan", "mela charukesi (26)"],
    1465 => ["mela ragavardhani (32)"],
    1479 => ["mela jalarnavam (38)"],
    1483 => ["mela bhavapriya (44)"],
    1485 => [
      "lydian diminished",
      "mela sanmukhapriya (56)",
      "aolian ♯4",
      "romani scale",
    ],
    1491 => ["mela namanarayani (50)"],
    1493 => ["lydian minor", "mela risabhapriya (62)"],
    1497 => ["mela jyotisvarupini (68)"],
    1499 => ["bebop locrian"],
    1619 => ["prometheus neopolitan"],
    1621 => ["prometheus"],
    1643 => ["locrian natural 6", "locrian ♯6"],
    1651 => ["oriental (b)"],
    1701 => ["dominant 7th"],
    1703 => ["mela vanaspati (4)"],
    1707 => ["javanese (pelog)", "mela natakapriya (10)", "pelog (javanese)"],
    1709 => ["dorian", "kafi theta", "mela kharaharapriya (22)"],
    1711 => ["jewish (adonai malakh)"],
    1715 => ["mela chakravakam (16)"],
    1717 => ["mixolydian", "khamaj theta", "mela harikambhoji (28)"],
    1721 => ["mela vagadhisvari (34)"],
    1725 => ["bebop dorian"],
    1735 => ["mela navanitam (40)"],
    1739 => ["mela sadvidhamargini (46)"],
    1741 => [
      "ukranian dorian",
      "romanian scale",
      "altered dorian",
      "roumanian minor",
      "mela hemavati (58)",
    ],
    1747 => "mela ramapriya (52)",
    1749 => [
      "acoustic",
      "lydian dominant",
      "mela vaschaspati (64)",
      "overtone dominant",
      "overtone",
    ],
    1753 => ["hungarian major", "mela nasikabhusani (70)"],
    1755 => [
      "octatonic",
      "second mode of limited transposition",
      "auxiliary diminished blues",
    ],
    2257 => ["hirajoshi", "chinese", "augmented"],
    2275 => "fifth mode of limited transposition",
    2419 => "persian",
    2457 => "augmented",
    2471 => "mela ganamurti (3)",
    2475 => ["minor neapolitan", "mela dhenuka (9)", "neopolitan"],
    2477 => ["harmonic minor", "mela kiravani (21)", "mohammedan"],
    2483 => [
      "enigmatic",
      "flamenco mode",
      "double harmonic",
      "bhairav theta",
      "byzantine",
      "hungarian gypsy persian",
      "mela mayamalavagaula (15)",
    ],
    2485 => ["mela sarasangi (27)"],
    2489 => ["mela gangeyabhusani (33)"],
    2503 => ["mela jhalavarali (39)"],
    2507 => ["mela subhapantuvarali (45)", "todi theta"],
    2509 => [
      "hungarian minor",
      "hungarian gypsy",
      "mela simhendramadhyama (57)",
    ],
    2515 => ["mela kamavarardhani (51)", "purvi theta"],
    2517 => ["mela latangi (63)"],
    2521 => ["mela dhatuvardhani (69)"],
    2535 => ["fourth mode of limited transposition"],
    2541 => ["algerian"],
    2727 => ["mela manavati (5)"],
    2731 => ["major neapolitan", "mela kokilapriya (11)", "neoploitan major"],
    2733 => [
      "heptatonia seconda",
      "melodic minor",
      "ascending melodic minor",
      "jazz minor",
      "hawaiian",
      "mela gaurimanohari (23)",
    ],
    2739 => ["mela suryakantam (17)"],
    2741 => [
      "major",
      "ionian",
      "bilaval theta",
      "ethiopian (a raray)",
      "mela dhirasankarabharana",
    ],
    2745 => ["mela sulini (35)"],
    2759 => ["mela pavani (41)"],
    2763 => ["mela suvarnangi (47)"],
    2765 => ["mela dharmavati (59)"],
    2771 => ["marva theta", "mela gamanasrama (53)"],
    2773 => ["lydian", "kalyan theta", "mela mechakalyani (65)"],
    2777 => ["lydian ♯2", "mela kosalam (71)"],
    2805 => ["japanese (ichikosucho)"],
    2869 => ["ionian augmented", "ionian ♯5"],
    2901 => ["lydian augmented"],
    2925 => ["diminished", "auxiliary diminished", "arabian a"],
    2989 => ["bebop minor"],
    2997 => ["bebop major"],
    3037 => ["nine tone scale"],
    3055 => ["seventh mode of limited transposition"],
    3239 => ["mela tanarupi (6)"],
    3243 => ["mela rupavati (12)"],
    3245 => ["mela varunapriya (24)"],
    3251 => ["mela hatakambari (18)"],
    3253 => ["mela naganandini (30)"],
    3257 => ["mela chalanata (36)"],
    3271 => ["mela raghupriya (42)"],
    3275 => ["mela divyamani (48)"],
    3277 => ["mela nitimati (60)"],
    3283 => ["mela visvambari (54)"],
    3285 => ["mela chitrambari (66)"],
    3289 => ["mela rasikapriya (72)"],
    3411 => ["enigmatic"],
    3413 => ["leading whole tone"],
    3419 => ["jewish (magan abot)"],
    3445 => ["sixth mode of limited transposition"],
    3549 => ["third mode of limited transposition"],
    3765 => ["bebop dominant"],
    3829 => ["japanese (taishikicho)"],
    4095 => ["chromatic"],
  }.freeze
end
